apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{  .Chart.Name }}
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- else if ((and (.Values.global)) (.Values.global.namespace)) }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{- if .Values.root_token }}
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: {{ .Values.root_token }}
        - name: VAULT_TOKEN
          value: {{ .Values.root_token }}
{{- else if .Values.global.vault }}
{{- if .Values.global.vault.root_token }}
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: {{ .Values.global.vault.root_token }}
        - name: VAULT_TOKEN
          value: {{ .Values.global.vault.root_token }}
{{- end }}
{{- end }}
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        ports:
{{- range $index, $node := .Values.service.ports }}
        - containerPort: {{ $node.port }}
{{- end }}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 30
        volumeMounts:
        - name: cosmic-vault-files
          mountPath: /files
          readOnly: true
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "/files/init.sh"]
      volumes:
      - name: cosmic-vault-files
        configMap:
          name: cosmic-vault-files