apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
data:
  config: {{ include "cosmic-billing-reporter.cosmic-billing-reporter.json" . | b64enc }}
