#
# Default values.yaml
#

global:
  devMode: false
  namespace: missioncriticalcloud
  registry: # for example: docker.io/   <-- don't forget the slash at the end
  elasticsearch:
    cluster_nodes:
    - http://elasticsearch:9200
  rabbitmq:
    username: root
    password: password
  vault:
    scheme: http
    host: cosmic-vault
    port: 8200
    backend: secret
    root_token: cosmic-vault-token # only when 'global.devMode: true'
    read_only_token: cosmic-vault-token
