namespace: missioncriticalcloud
private_registry:
dev_mode: false

services:
  - rabbitmq
  - elasticsearch
  - cosmic-vault
  - cosmic-config-server
  - cosmic-usage-api

configmaps:
  - init-container

secrets:
  - rabbitmq
  - logstash
  - cosmic-config-server
  - cosmic-metrics-collector
  - cosmic-usage-api

deployments:
  - rabbitmq
  - elasticsearch
  - logstash
  - cosmic-vault
  - cosmic-config-server
  - cosmic-metrics-collector
  - cosmic-usage-api

rabbitmq:
  username: mr_bunny
  password: carrots

cosmic_config_server:
  vault:
    scheme: http
    host: cosmic-vault
    port: 8200
    backend: secret
    health_token: cosmic-vault-token

cosmic_metrics_collector:
  vault_token: cosmic-vault-token

cosmic_usage_api:
  vault_token: cosmic-vault-token

cosmic_vault:
  root_token: cosmic-vault-token
