#
# Default values.yaml
#

grafana:
  server:
    adminUser: root
    adminPassword: password
    serviceType: NodePort
    nodePort: 31003
    setDatasource:
      enabled: true
      image: appropriate/curl:latest
      datasource:
        name: cosmic-metrics-index
        type: elasticsearch
        database: "[cosmic-metrics-]YYYY.MM.DD"
        jsonData: '\"esVersion\": 2, \"interval\": \"Daily\", \"timeField\": \"@timestamp\"'
        url: http://elasticsearch.cosmic:9200
        access: proxy
        isDefault: true
      restartPolicy: OnFailure

global:
  devMode: false
  namespace: missioncriticalcloud
  registry: # for example: docker.io/   <-- don't forget the slash at the end
  elasticsearch:
    clusterNodes:
    - http://elasticsearch:9200
  rabbitmq:
    username: root
    password: password
  vault:
    scheme: http
    host: cosmic-vault
    port: 8200
    backend: secret
    rootToken: cosmic-vault-token # only when 'global.devMode: true'
    readOnlyToken: cosmic-vault-token
