{{- define "deployments.cosmic-config-server" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cosmic-config-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cosmic-config-server
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
              "name": "install",
              "image": "busybox",
              "command": ["/bin/sh"],
              "args": [
                  "/scripts/readiness-probe.sh",
                  "-h", {{ .Values.cosmic_config_server.vault.host | quote }},
                  "-p", {{ .Values.cosmic_config_server.vault.port | quote }},
                  "-P", "/v1/sys/health"
              ],
              "imagePullPolicy": "IfNotPresent",
              "volumeMounts": [{
                  "name": "init-container-files",
                  "mountPath": "/scripts",
                  "readOnly": true
              }]
          }
          {{- if .Values.dev_mode }}
          ,
          {
              "name": "loadconfig",
              "image": "busybox",
              "command": ["/bin/sh"],
              "args": [
                  "/scripts/post-vault-config.sh",
                  "-h", {{ .Values.cosmic_config_server.vault.host | quote }},
                  "-p", {{ .Values.cosmic_config_server.vault.port | quote }},
                  "-H", "X-Vault-Token: {{ .Values.cosmic_vault.root_token }}"
              ],
              "imagePullPolicy": "IfNotPresent",
              "volumeMounts": [{
                  "name": "init-container-files",
                  "mountPath": "/scripts",
                  "readOnly": true
              }]
          }
          {{- end }}
          ]'
    spec:
      containers:
      - name: cosmic-config-server
        image: {{ .Values.private_registry }}missioncriticalcloud/cosmic-config-server
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            httpHeaders:
                - name: X-Config-Token
                  value: {{ .Values.cosmic_config_server.vault.health_token }}
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 30
        env:
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            secretKeyRef:
              name: cosmic-config-server
              key: config
        ports:
        - containerPort: 8080
      volumes:
      - name: init-container-files
        configMap:
          name: init-container-files
{{- end -}}
