{{- define "deployments.cosmic-vault" -}}
{{- if .Values.dev_mode -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cosmic-vault
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cosmic-vault
    spec:
      containers:
      - name: cosmic-vault
        image: vault:latest
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: {{ .Values.vault.root_token }}
        - name: VAULT_TOKEN
          value: {{ .Values.vault.root_token }}
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        ports:
        - containerPort: 8200
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 30
        volumeMounts:
        - name: cosmic-vault-files
          mountPath: /files
          readOnly: true
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "/files/init.sh"]
      volumes:
      - name: cosmic-vault-files
        configMap:
          name: cosmic-vault-files
{{- end -}}
{{- end -}}
