{{- define "deployments.cosmic-metrics-collector" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cosmic-metrics-collector
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cosmic-metrics-collector
      annotations:
        pod.beta.kubernetes.io/init-containers: |
          [{
            "name": "config-server-health-checker",
            "image": "python:alpine",
            "command": ["/usr/local/bin/python"],
            "args": [
              "/scripts/readiness-probe.py",
              "--host", "cosmic-config-server",
              "--port", "8080",
              "--path", "/health",
              "--headers", "{\"X-Config-Token\": \"{{ .Values.vault.read_only_token }}\"}"
            ],
            "imagePullPolicy": "IfNotPresent",
            "volumeMounts": [{
              "name": "init-container-scripts",
              "mountPath": "/scripts",
              "readOnly": true
            }]
          }]
    spec:
      containers:
      - name: cosmic-metrics-collector
        image: {{ .Values.registry }}missioncriticalcloud/cosmic-metrics-collector
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            secretKeyRef:
              name: cosmic-metrics-collector
              key: config
      volumes:
      - name: init-container-scripts
        configMap:
          name: init-container-scripts
{{- end -}}
