{{- define "deployments.cosmic-metrics-collector" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cosmic-metrics-collector
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cosmic-metrics-collector
      annotations:
        pod.beta.kubernetes.io/init-containers: '[{
            "name": "install",
            "image": "busybox",
            "command": ["/bin/sh"],
            "args": ["/scripts/readiness-probe.sh", "cosmic-config-server", "8080", "/health", "200", "X-Config-Token: {{ .Values.cosmic_config_server.vault.health_token }}"],
            "imagePullPolicy": "IfNotPresent",
            "volumeMounts": [{
                "name": "init-container-files",
                "mountPath": "/scripts",
                "readOnly": true
            }]
        }]'
    spec:
      containers:
      - name: cosmic-metrics-collector
        image: {{ .Values.private_registry }}missioncriticalcloud/cosmic-metrics-collector
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            secretKeyRef:
              name: cosmic-metrics-collector
              key: config
      volumes:
      - name: init-container-files
        configMap:
          name: init-container-files
{{- end -}}
