{{- define "deployments.elasticsearch" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:2
        ports:
        - containerPort: 9200
        - containerPort: 9300
{{- end -}}
