{{- define "deployments.logstash" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: logstash:{{ .Values.logstash.image_tag }}
{{- if .Values.dev_mode }}
        args: ["-f", "/files/logstash.conf", "--debug"]
{{- else }}
        args: ["-f", "/files/logstash.conf"]
{{- end }}
        volumeMounts:
        - name: logstash-files
          mountPath: /files
          readOnly: true 
      volumes:
      - name: logstash-files
        secret:
          secretName: logstash-files
{{- end -}}
