apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- else if ((and (.Values.global)) (.Values.global.namespace)) }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if or .Values.dev_mode (and .Values.global .Values.global.dev_mode) }}
        args: ["-f", "/files/logstash.conf", "--debug"]
{{- else }}
        args: ["-f", "/files/logstash.conf"]
{{- end }}
        volumeMounts:
        - name: logstash-files
          mountPath: /files
          readOnly: true
      volumes:
      - name: logstash-files
        secret:
          secretName: logstash-files
