apiVersion: v1
kind: Secret
metadata:
  name: logstash-files
  namespace: {{ .Values.global.namespace }}
data:
  cosmic-metrics-template.json: {{ include "secrets.logstash-files.cosmic-metrics-template.json" . | b64enc }}
  logstash.conf: {{ include "secrets.logstash-files.logstash.conf" . | b64enc }}

