apiVersion: v1
kind: Secret
metadata:
  name: logstash-files
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- else if ((and (.Values.global)) (.Values.global.namespace)) }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
data:
  cosmic-metrics-template.json: {{ include "secrets.logstash-files.cosmic-metrics-template.json" . | b64enc }}
  logstash.conf: {{ include "secrets.logstash-files.logstash.conf" . | b64enc }}

