apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
data:
  config: {{ include "secrets.cosmic-config-files.cosmic-usage-api.json" . | b64enc }}
