{{- define "services.cosmic-vault" -}}
{{- if .Values.dev_mode -}}
apiVersion: v1
kind: Service
metadata:
  name: cosmic-vault
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cosmic-vault
  ports:
    - port: 8200
      name: http-port
      protocol: TCP
      targetPort: 8200
      nodePort: 30131
  type: NodePort
{{- end -}}
{{- end -}}
