{{- define "services.cosmic-config-server" -}}
apiVersion: v1
kind: Service
metadata:
  name: cosmic-config-server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cosmic-config-server
  ports:
    - port: 8080
      protocol: TCP
  {{- if .Values.dev_mode }}
      nodePort: 31100
  type: NodePort
  {{- end }}
{{- end -}}
