{{- define "services.cosmic-usage-api" -}}
apiVersion: v1
kind: Service
metadata:
  name: cosmic-usage-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cosmic-usage-api
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 31001
  type: NodePort
{{- end -}}
