{{- define "services.elasticsearch" -}}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: elasticsearch
  ports:
    - name: "http"
      port: 9200
      protocol: TCP
      {{- if .Values.dev_mode }}
      nodePort: 30121
      {{- end }}
    - name: "transport"
      port: 9300
      protocol: TCP
  {{- if .Values.dev_mode }}
  type: NodePort
  {{- end }}
{{- end -}}
