{{- define "services.elasticsearch" -}}
{{- if .Values.dev_mode -}}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: elasticsearch
  ports:
    - name: "http"
      port: 9200
      protocol: TCP
      nodePort: 31102
    - name: "transport"
      port: 9300
      protocol: TCP
  type: NodePort
{{- end -}}
{{- end -}}
