apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        pod.beta.kubernetes.io/init-containers: |
          [{
            "name": "usage-api-health-checker",
            "image": "python:alpine",
            "command": ["/usr/local/bin/python"],
            "args": [
              "/scripts/readiness-probe.py",
              "--host", "cosmic-usage-api",
              "--port", "8080",
              "--path", "/health"
            ],
            "imagePullPolicy": "IfNotPresent",
            "volumeMounts": [{
              "name": "init-container-scripts",
              "mountPath": "/scripts",
              "readOnly": true
            }]
          }]
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.registry }}{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: COSMIC_USAGE_API_BASE_URL
          value: {{ .Values.usageApiBaseUrl }}
        - name: COSMIC_USAGE_UI_CPU_PRICE
          value: {{ .Values.usageUICPUPrice }}
        - name: COSMIC_USAGE_UI_MEMORY_PRICE
          value: {{ .Values.usageUIMemoryPrice }}
        - name: COSMIC_USAGE_UI_STORAGE_PRICE
          value: {{ .Values.usageUIStoragePrice }}
        - name: COSMIC_USAGE_UI_IPV4_PRICE
          value: {{ .Values.usageUIIPv4Price }}
        - name: COSMIC_USAGE_UI_SERVICE_FEE
          value: {{ .Values.usageUIServiceFee }}
        - name: COSMIC_USAGE_UI_INNOVATION_FEE
          value: {{ .Values.usageUIInnovationFee }}
      volumes:
      - name: init-container-scripts
        configMap:
          name: init-container-scripts
