apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- else if ((and (.Values.global)) (.Values.global.namespace)) }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        pod.beta.kubernetes.io/init-containers: |
          [{
            "name": "config-server-health-checker",
            "image": "python:alpine",
            "command": ["/usr/local/bin/python"],
            "args": [
              "/scripts/readiness-probe.py",
              "--host", "cosmic-config-server",
              "--port", "8080",
              "--path", "/health",
              "--headers", "{\"X-Config-Token\": \"{{ .Values.global.vault.read_only_token }}\"}"
            ],
            "imagePullPolicy": "IfNotPresent",
            "volumeMounts": [{
              "name": "init-container-scripts",
              "mountPath": "/scripts",
              "readOnly": true
            }]
          }]
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            secretKeyRef:
              name: cosmic-metrics-collector
              key: config
      volumes:
      - name: init-container-scripts
        configMap:
          name: init-container-scripts
