apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
data:
  config: {{ include "cosmic-metrics-collector.cosmic-metrics-collector.json" . | b64enc }}
