# Default values for cosmic-vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: vault
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: NodePort
  ports:
    - port: 8200
      protocol: TCP
      nodePort: 31101
cosmicScanInterval: "0 */15 * * * *"
cosmicTokenEncryptionKey: "D48F19E22D5E1BDA"
cosmicTokenEncryptionSalt: "5C0744940B5C369B"
cosmicTokenEncryptionTtl: "3600000"
rootToken:

# Following values are required to have sane values
global:
  namespace:
