# Default values for cosmic-vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: vault
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: NodePort
  ports:
    - port: 8200
      protocol: TCP
      nodePort: 31101

cosmic:
  billViewer:
    cpuPrice: "1"
    memoryPrice: "1"
    storagePrice: "1"
    publicIpPrice: "1"
    serviceFee: "5"
    InnovationFee: "5"
  billingReporter:
    mailHost: "localhost"
    mailPort: "25"
    mailUsername: "admin"
    mailPassword: "password"
    tokenEncryptionKey: "D48F19E22D5E1BDA"
    tokenEncryptionSalt: "5C0744940B5C369B"
    scanInterval: "0 */15 * * * *"
    billViewerBaseUrl: "http://localhost:7003/?token=%s&path=%s"
    fromEmailAddress: "cosmic-billing-reporter@localhost"
    tokenTtl: "3600000"
  metricsCollector:
    scanInterval: "0 */15 * * * *"
  usageApi:
    scanInterval: "0 */15 * * * *"
    tokenEncryptionKey: "D48F19E22D5E1BDA"
    tokenEncryptionSalt: "5C0744940B5C369B"

rootToken:

# Following values are required to have sane values
global:
  namespace:
