{{- define "secrets.rabbitmq" -}}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Values.namespace }}
data:
  username: {{ .Values.rabbitmq.username | b64enc }}
  password: {{ .Values.rabbitmq.password | b64enc }}
{{- end -}}
