# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace:
replicaCount: 1
image:
  name: elasticsearch
  tag: 2
  pullPolicy: IfNotPresent
service:
  type: NodePort
  ports:
    - name: http
      port: 9200
      protocol: TCP
      nodePort: 31102
    - name: transport
      port: 9300
      protocol: TCP

# Following values are required to have sane values
global:
  namespace:
