apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        pod.beta.kubernetes.io/init-containers: |
          [{
            "name": "vault-health-checker",
            "image": "python:alpine",
            "command": ["/usr/local/bin/python"],
            "args": [
              "/scripts/readiness-probe.py",
{{- if eq .Values.global.vault.scheme "https" }}
              "--tls",
{{- end }}
              "--host", {{ .Values.global.vault.host | quote }},
              "--port", {{ .Values.global.vault.port | quote }},
              "--path", "/v1/sys/health"
            ],
            "imagePullPolicy": "IfNotPresent",
            "volumeMounts": [{
              "name": "init-container-scripts",
              "mountPath": "/scripts",
              "readOnly": true
            }]
          }]
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            httpHeaders:
            - name: X-Config-Token
              value: {{ .Values.global.vault.read_only_token }}
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 30
        env:
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            secretKeyRef:
              name: cosmic-config-server
              key: config
        ports:
        - containerPort: 8080
      volumes:
      - name: init-container-scripts
        configMap:
          name: init-container-scripts

