apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- else if ((and (.Values.global)) (.Values.global.namespace)) }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
data:
  config: {{ include "secrets.cosmic-config-files.cosmic-config-server.json" . | b64enc }}
