apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- else if ((and (.Values.global)) (.Values.global.namespace)) }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
    - port: 8080
      protocol: TCP
  {{- if .Values.global.dev_mode }}
      nodePort: 31100
  type: NodePort
  {{- end }}
  selector:
    app: {{ .Chart.Name }}
