apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
  {{- if .Values.global.devMode }}
      nodePort: 31100
  type: NodePort
  {{- end }}
  selector:
    app: {{ .Chart.Name }}
