# Default values for cosmic-bill-viewer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: missioncriticalcloud/cosmic-bill-viewer
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 31002

# Following values are required to have sane values
global:
  namespace:
  vault:
    readOnlyToken:
