# Default values for cosmic-bill-viewer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: missioncriticalcloud/cosmic-bill-viewer
  tag: latest
  pullPolicy: IfNotPresent
service:

# Following values are required to have sane values
global:
  namespace:
