apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Values.global.namespace }}
data:
{{- if .Values.username }}
  username: {{ .Values.username | b64enc }}
{{- else if .Values.global.rabbitmq }}
{{- if .Values.global.rabbitmq.username }}
  username: {{ .Values.global.rabbitmq.username | b64enc }}
{{- end }}
{{- end }}
{{- if .Values.password }}
  password: {{ .Values.password | b64enc }}
{{- else if .Values.global.rabbitmq }}
{{- if .Values.global.rabbitmq.password }}
  password: {{ .Values.global.rabbitmq.password | b64enc }}
{{- end }}
{{- end }}
