apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- else if ((and (.Values.global)) (.Values.global.namespace)) }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
{{- if or .Values.dev_mode (and .Values.global .Values.global.dev_mode) }}
  type: NodePort
{{- end }}
  ports:
    - name: "epmd"
      port: 4369
      protocol: TCP
    - name: "amqp-1"
      port: 5671
      protocol: TCP
    - name: "amqp-2"
      port: 5672
      protocol: TCP
    - name: "erlang"
      port: 25672
      protocol: TCP
    - name: "management"
      port: 15672
      protocol: TCP
{{- if or .Values.dev_mode (and .Values.global .Values.global.dev_mode) }}
      nodePort: 31103
{{- end }}
  selector:
    app: {{ .Chart.Name }}
