apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
spec:
{{- if .Values.global.devMode }}
  type: NodePort
{{- end }}
  ports:
    - name: "epmd"
      port: 4369
      protocol: TCP
    - name: "amqp-1"
      port: 5671
      protocol: TCP
    - name: "amqp-2"
      port: 5672
      protocol: TCP
    - name: "erlang"
      port: 25672
      protocol: TCP
    - name: "management"
      port: 15672
      protocol: TCP
{{- if .Values.global.devMode }}
      nodePort: 31103
{{- end }}
  selector:
    app: {{ .Chart.Name }}
