apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 31002
  type: NodePort
  selector:
    app: {{ .Chart.Name  }}
