# Default values for rabbitmq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: rabbitmq
  tag: management
  pullPolicy: IfNotPresent
service:
username:
password:

